function lowpass = low_fil(x , y)
%UNTITLED Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.9 and Signal Processing Toolbox 8.5.
% Generated on: 12-Jun-2023 18:25:47

% Equiripple Lowpass filter designed using the FIRPM function.

% All frequency values are in Hz.
Fs = x;  % Sampling Frequency

Fpass = y+100;             % Passband Frequency
Fstop = y+120;             % Stopband Frequency
Dpass = 0.057501127785;  % Passband Ripple
Dstop = 0.0001;          % Stopband Attenuation
dens  = 20;              % Density Factor

% Calculate the order from the parameters using FIRPMORD.
[N, Fo, Ao, W] = firpmord([Fpass, Fstop]/(Fs/2), [1 0], [Dpass, Dstop]);

% Calculate the coefficients using the FIRPM function.
b  = firpm(N, Fo, Ao, W, {dens});
lowpass = dfilt.dffir(b);

% [EOF]
